spring.application.name=FreedomDMPLunch
server.port=8888

telegram.bot.username=DMPLunchCollectorBot
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent
